---
# tasks file for genitic_create_group_user
- name: Make sure a group named "xxx" variable in defaults folder.
  group:
    name: "{{ admin_group }}"
    state: present
  become: yes
- name: Allow named group to have paswordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ admin_group }}'
    line: '%{{ admin_group }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: yes
- name: Add sudoers users to named group
  user:
    name: "{{ admin_user }}"
    groups: "{{ admin_group }}"
    state: present
    password: "{{ default_user_password | password_hash('sha512','A512') }}"
  become: yes
#- name: Set up authorized keys for the deployer user
#  authorized_key: user=deployer key='{{item}}'
#  with_file:
#    - ~/.ssh/id_rsa.pub
